version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/league_highlight:cached
      - bundle:/usr/local/bundle
    ports:
      - 3001:3000
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql

  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444

volumes:
  bundle:
  mysql_data:
